apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-04T17:15:00Z
  generation: 2
  labels:
    app: city-pantry-backend
  name: city-pantry-backend-deployment
  namespace: default
  resourceVersion: "147292"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/city-pantry-backend-deployment
  uid: 06cbac42-c7f9-11e8-9b63-42010a840187
spec:
  replicas: 2
  selector:
    matchLabels:
      app: city-pantry-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: city-pantry-backend
    spec:
      containers:
      - image: gcr.io/phoenix-0018/city-pantry-backend:v0.0.1
        imagePullPolicy: IfNotPresent
        name: city-pantry-backend-deployment
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-10-05T11:17:21Z
    lastUpdateTime: 2018-10-05T11:17:21Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
